# ─────────────── Helios Makefile ───────────────
# Location  :   scripts/Makefile   (or project root)
# Purpose   :   Let “make” build the Gradle project for OpenBench
# Requires  :   ./gradlew   (Gradle wrapper generated by Gradle)
# Targets   :
#   make / make build   – build the engine
#   make clean          – remove all build artefacts
# ------------------------------------------------

GRADLE   := ./gradlew           # use the wrapper; falls back to system Gradle
APP_NAME := Helios
APP_DIR  := build/install/$(APP_NAME)
BIN      := $(APP_DIR)/bin/$(APP_NAME)

# ── default target ──────────────────────────────
.PHONY: all
all: $(BIN)

# Build the distribution and ensure the launcher script is executable
$(BIN):
	@echo ">> Building $(APP_NAME) with Gradle"
	bash $(GRADLE) --no-daemon --console=plain installDist
	@echo ">> Marking $(BIN) executable for OpenBench"
	chmod +x $(BIN)

# Handy explicit build alias
.PHONY: build
build: all

# Clean everything Gradle produced
.PHONY: clean
clean:
	@echo ">> Cleaning Gradle artefacts"
	bash $(GRADLE) --no-daemon --console=plain clean
	rm -rf build
# ────────────────────────────────────────────────
