# ─────────────── Helios Makefile ───────────────
# Location  :   scripts/Makefile
# Purpose   :   let “make” build the Gradle project for OpenBench
# Requires  :   ./gradlew   (Gradle wrapper generated by Gradle)
# Targets   :
#   make           – default, builds the engine
#   make clean     – removes all build artefacts
# ------------------------------------------------

GRADLE   := ./gradlew           # use the wrapper; falls back to system Gradle
APP_NAME := Helios
APP_DIR  := build/install/$(APP_NAME)
BIN      := $(APP_DIR)/bin/$(APP_NAME)

# ── default target ──────────────────────────────
.PHONY: all
all: $(BIN)

# the binary appears after “installDist”
$(BIN):
	bash $(GRADLE) --no-daemon --console=plain installDist

# handy explicit build alias
.PHONY: build
build: all

# clean everything Gradle produced
.PHONY: clean
clean:
	$(GRADLE) --no-daemon --console=plain clean
	rm -rf build
# ────────────────────────────────────────────────
