name: HQ speed regression          # .github/workflows/hq-speed-regression.yml

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**/MoveGeneratorImpl.java'
      - '**/MoveGenerator.java'
      - '**/MoveGeneratorBenchmark.java'
      - '**/MoveGeneratorPerftAllTest.java'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # ─────────────────────────────────────────────────────────
  perft-all:                          # ← ❶ correctness gate
    runs-on: windows-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: actions/cache@v4          # Gradle cache (unchanged)
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Run MoveGeneratorPerftAllTest
        shell: bash
        run: |
          set -euo pipefail
          # This runs ONLY the heavy test-class; no need for -PrunPerft
          ./gradlew --no-daemon --console=plain test \
                     --tests 'core.MoveGeneratorPerftAllTest'

  # ─────────────────────────────────────────────────────────
  bench:                              # ← ❷ runs only if ❶ passes
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show diff between base & PR
        shell: bash
        run: |
          git fetch origin "${{ github.base_ref }}"
          echo "Files affecting path-filter:"
          git diff --name-only "origin/${{ github.base_ref }}" "${{ github.sha }}"

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: actions/cache@v4          # Gradle cache (unchanged)
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      # ────────── benchmark base (main) ──────────
      - name: Benchmark base branch
        shell: bash
        run: |
          set -euo pipefail
          echo "▶ Benchmarking origin/${{ github.base_ref }}"
          git checkout "origin/${{ github.base_ref }}"
          # Run ONLY MoveGeneratorBenchmark
          ./gradlew --no-daemon --console=plain jmh \
                     -Pjmh.includes='.*MoveGeneratorBenchmark.*' | tee base.txt
          cp build/results/jmh/results.csv base.csv

      # ────────── benchmark PR HEAD ──────────
      - name: Benchmark PR branch
        shell: bash
        run: |
          set -euo pipefail
          echo "▶ Benchmarking PR head ${{ github.sha }}"
          git checkout "${{ github.sha }}"
          ./gradlew --no-daemon --console=plain jmh \
                     -Pjmh.includes='.*MoveGeneratorBenchmark.*' | tee pr.txt
          cp build/results/jmh/results.csv pr.csv

      # ────────── compare results ─────────
      - name: Compare nodes-per-second
        shell: bash
        run: |
          set -euo pipefail
          python scripts/compare_jmh.py base.csv pr.csv
