name: HQ speed regression

on:
  pull_request:
    # fire whenever any of the “HQ” sources or benchmarks change
    paths:
      - '**/MoveGeneratorHQ.java'
      - '**/MoveGeneratorHQTest.java'
      - '**/HQBenchmark.java'

permissions:
  contents: read        # required for checkout in PRs from forks

jobs:
  # ────────────────────────────────────────────────
  bench:
    runs-on: windows-latest
    timeout-minutes: 60        # adjust if your benches are slower

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # we need base / head commits

      - name: Set up Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # -------- benchmark base (merge-base with main) ----------
      - name: Benchmark base branch
        shell: bash
        run: |
          set -euo pipefail
          git checkout "origin/${{ github.base_ref }}"
          ./gradlew --no-daemon \
            -Djmh.warmupIterations=5 \
            -Djmh.iterations=5 \
            -Dcases=10 \
            jmh -PbenchInclude=HQBenchmark \
            --console=plain > base.txt

      # -------- benchmark PR HEAD ----------
      - name: Benchmark PR branch
        shell: bash
        run: |
          set -euo pipefail
          git checkout "${{ github.sha }}"
          ./gradlew --no-daemon \
            -Djmh.warmupIterations=5 \
            -Djmh.iterations=5 \
            -Dcases=10 \
            jmh -PbenchInclude=HQBenchmark \
            --console=plain > pr.txt

      # -------- compare ----------
      - name: Diff the two runs
        shell: bash
        run: |
          set -euo pipefail
          python scripts/compare_jmh.py base.txt pr.txt

  # ────────────────────────────────────────────────
  perft:
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      RUN_PERFT: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Run perft tests
        shell: bash
        run: |
          set -euo pipefail
          ./gradlew --no-daemon test
