name: HQ speed regression

on:
  pull_request:
    # fire whenever any of the HQ-related sources / tests / benches change
    paths:
      - '**/MoveGeneratorHQ.java'
      - '**/MoveGeneratorHQTest.java'
      - '**/HQBenchmark.java'

permissions:
  contents: read       # checkout for PRs from forks

# ─────────────────────────────────────────────────────────
jobs:

  bench:
    runs-on: windows-latest
    timeout-minutes: 300           # 5 h = plenty for 2 × 1 h benches + overhead

    steps:
      # ---------- checkout ----------
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0           # we need base + head

      # ---------- toolchain ----------
      - name: Set up Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # ---------- benchmark BASE (main) ----------
      - name: Benchmark base branch
        shell: bash
        run: |
          set -euo pipefail
          echo "▶ running benchmark on origin/${{ github.base_ref }}"
          git checkout "origin/${{ github.base_ref }}"
          ./gradlew --no-daemon --info jmh \
            -PbenchInclude=HQBenchmark \
            -Djmh.warmupIterations=3 \
            -Djmh.iterations=10 \
            -Djmh.fork=2 \
            -Dcases=10 \
            --console=plain > base.txt

      # ---------- benchmark PR HEAD ----------
      - name: Benchmark PR branch
        shell: bash
        run: |
          set -euo pipefail
          echo "▶ running benchmark on PR head ${{ github.sha }}"
          git checkout "${{ github.sha }}"
          ./gradlew --no-daemon --info jmh \
            -PbenchInclude=HQBenchmark \
            -Djmh.warmupIterations=3 \
            -Djmh.iterations=10 \
            -Djmh.fork=2 \
            -Dcases=10 \
            --console=plain > pr.txt

      # ---------- compare ----------
      - name: Diff the two runs
        shell: bash
        run: |
          set -euo pipefail
          python scripts/compare_jmh.py base.txt pr.txt

  # ────────────────────────────────────────────────────────
  perft:
    runs-on: windows-latest
    timeout-minutes: 120
    env:
      RUN_PERFT: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Run perft tests
        shell: bash
        run: |
          set -euo pipefail
          ./gradlew --no-daemon --info test
