name: HQ speed regression

on:
  pull_request:
    paths:                              # only when HQ itself changed
      - 'src/**/MoveGeneratorHQ.java'

jobs:
  bench:
    runs-on: windows-2022         # or self-hosted / bigger runner
    timeout-minutes: 60                 # safety net

    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }          # we need the merge-base

    - name: Set up Temurin 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

    # ---------- run benchmark on base (main) ----------
    - name: Benchmark base branch
      run: |
        git checkout origin/${{ github.base_ref }}
        ./gradlew --no-daemon \
           -Djmh.warmupIterations=5 \
           -Djmh.iterations=5 \
           -Dcases=10 \
           jmh -PbenchInclude=HQBenchmark \
           --console=plain > base.txt

    # ---------- run benchmark on PR HEAD ----------
    - name: Benchmark PR branch
      run: |
        git checkout ${{ github.sha }}
        ./gradlew --no-daemon \
           -Djmh.warmupIterations=5 \
           -Djmh.iterations=5 \
           -Dcases=10 \
           jmh -PbenchInclude=HQBenchmark \
           --console=plain > pr.txt

    # ---------- compare -----------
    - name: Diff the two runs
      run: python scripts/compare_jmh.py base.txt pr.txt

  perft:
    runs-on: windows-2022
    env:
      RUN_PERFT: "true"
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

      - name: Run perft tests
        run: |
          ./gradlew --no-daemon test

